server:
  port: 8888

# MySQL
spring:
  datasource:
    url: jdbc:mysql://localhost:3306/test?serverTimezone=UTC
    username: root
    password: root
  jpa:
    hibernate:
      ddl-auto: none
    open-in-view: false
    show-sql: true
  redis:
    host: 192.168.6.129
    port: 6379
    connectionTimeout: 5000
    database: 0
  thymeleaf:
    encoding: utf-8
    content-type: text/html
    cache: false
    prefix: classpath:/templates/
    suffix: .html

logging:
  level:
    root: info
